name: Build app

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch: # Allows the action to be run manually from GitHub UI

jobs:
  build:
    name: Build the NextJS app
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
